fix: [MDS-331] Breadcrumb v2
coingaming/moon pull request #502
Opened 2023-01-06 11:41 UTC by tkullisaar

- Added Aria support for Breadcrumb v2
- Added Deprecation warning for Breadcrumb v1

2023-01-06 11:54 UTC, phgrey commented
1. aria-current="page" should be only on the last breadcrumb (e.g. Tabs), not previous (e.g. Moon, Components v2) and so on
2. where is aria-label="Breadcrumb" ?

2023-01-06 11:55 UTC, phgrey requested changes
1. aria-current="page" should be only on the last breadcrumb (e.g. Tabs), not previous (e.g. Moon, Components v2) and so on
2. where is aria-label="Breadcrumb" ?

2023-01-08 20:19 UTC, tkullisaar commented
> 1. aria-current="page" should be only on the last breadcrumb (e.g. Tabs), not previous (e.g. Moon, Components v2, and so on)
> 2. where is aria-label="Breadcrumb" ?

aria-label="Breadcrumb" already there.

2023-01-09 08:09 UTC, phgrey approved these changes

2023-01-09 08:10 UTC, merged