MDS-333 Accordion-v2
coingaming/moon pull request #506
Opened 2023-01-09 15:48 UTC by phgrey

- subj
- Tooltip fix - no js, css only
- some merge_class improvement

2023-01-09 15:50 UTC, margusp2heathmont commented on lib/moon/design/accordion.ex
> +    # IO.puts("ON_CHANGE_ACCORDION ############ params = #{inspect(_params, pretty: true)}")
Please not comments in codebase.

2023-01-09 15:51 UTC, margusp2heathmont commented on lib/moon/helpers/styled.ex
>      end
All this module should be deleted.

2023-01-09 15:52 UTC, margusp2heathmont commented on lib/moon_web/pages/design/accordion_page.ex
> +      <ExampleAndCode title="One item open at a time and Disabled" {...rndid()}>
This will update on each render?

2023-01-09 15:52 UTC, margusp2heathmont commented on lib/moon_web/pages/design/accordion_page.ex
> +      <ExampleAndCode title="One item open at a time and Disabled" {...rndid()}>
Not ideal behaviour.

2023-01-09 15:52 UTC, margusp2heathmont requested changes
Please see comments.

2023-01-09 20:42 UTC, phgrey commented on lib/moon_web/pages/design/accordion_page.ex
> +      <ExampleAndCode title="One item open at a time and Disabled" {...rndid()}>
thanks, haven't thought about

2023-01-10 10:02 UTC, tkullisaar approved these changes

2023-01-10 10:10 UTC, margusp2heathmont approved these changes

2023-01-10 10:11 UTC, merged