[MDS-519] Carousel v2 with intersection observer
coingaming/moon pull request #644
Opened 2023-05-25 16:06 UTC by tkullisaar

2023-05-29 07:33 UTC, karl-kallavus requested changes
Please install `prettier`. I see only tine indentation knit picks and minor refactoring.

2023-05-29 07:33 UTC, karl-kallavus commented on assets/js/hooks/carousel.js
> +        this.scrollIntoViewSmoothly = scrollIntoView;
minor: identation

2023-05-29 07:33 UTC, karl-kallavus commented on assets/js/hooks/carousel.js
> +            if (scrollToIndex !== -1) {
identation

2023-05-29 07:33 UTC, karl-kallavus commented on assets/js/hooks/carousel.js
> +            if (scrollToIndex !== -1) {
this and line 65 could be a function

2023-05-29 07:33 UTC, karl-kallavus commented on assets/js/hooks/carousel.js
> +                entry.intersectionRatio >= 0.75
make a constant for 0.75

2023-05-29 07:35 UTC, karl-kallavus commented on assets/js/hooks/carousel.js
> +        if (document && "scrollBehavior" in document.documentElement.style) {
NB: I need to double check how it actually works. I think we will discuss it on our call @tkullisaar

2023-05-30 09:57 UTC, phgrey approved these changes

2023-05-30 11:48 UTC, karl-kallavus approved these changes
LGTM

2023-05-30 11:49 UTC, karl-kallavus commented
Still we need to fix scroll-snap position thought

2023-06-01 07:58 UTC, karl-kallavus commented on lib/moon/design/carousel/reel.ex
> +          "[&>li]:list-none before:absolute [&>li]:before:content-[&quot;200B&quot;]",
**[&>li]:** before:absolute

2023-06-01 07:58 UTC, karl-kallavus commented on lib/moon/design/carousel/reel.ex
> +          "snap-x rtl:flex-row-reverse",
`snap-mandatory` is missing, I assume that might be the case

2023-06-02 11:50 UTC, merged